# Generated by Django 3.2 on 2021-05-05 16:26

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
