# Generated by Django 3.2 on 2021-05-05 17:13

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210505_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'страница', 'verbose_name_plural': 'страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_de',
            field=models.CharField(max_length=600, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_ru',
            field=models.CharField(max_length=600, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=django_quill.fields.QuillField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_de',
            field=django_quill.fields.QuillField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_ru',
            field=django_quill.fields.QuillField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
