# Generated by Django 3.2 on 2021-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Название альбома'),
        ),
        migrations.AddField(
            model_name='galery',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название альбома'),
        ),
    ]
