# Generated by Django 3.2 on 2021-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('page_from', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'сотрудника', 'verbose_name_plural': 'сотрудники'},
        ),
    ]
