# Generated by Django 3.2 on 2021-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210421_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
