# Generated by Django 3.2 on 2021-05-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_proposal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='first_name_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='notation_de',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='notation_ru',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
