# Generated by Django 3.2 on 2021-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210501_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
