# Generated by Django 3.2 on 2021-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210501_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='staff_images/', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='notation',
            field=models.CharField(max_length=900, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='notation_de',
            field=models.CharField(max_length=900, null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='notation_ru',
            field=models.CharField(max_length=900, null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Должность'),
        ),
    ]
